version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - sqlite3
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  
