build:
  docker:
    web: .
services:
  web:
    image: registry.heroku.com/myapp/web
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - sqlite3
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
